### ISSUE TITLE
invalid load key, 'D'.

### ISSUE THREAD

**Issue by j-kawasaki** [j-kawasaki/shooting_simulator#8]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/mnt/c/Users/j-kawasaki/.pyenv/versions/3.7.1/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/mnt/c/Users/j-kawasaki/.pyenv/versions/3.7.1/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/c/Users/j-kawasaki/git/shooting_simulator/server/NetworkClient.py", line 105, in handler    raw_data = pickle.loads(pickled_data)
_pickle.UnpicklingError: invalid load key, 'D'.

**Comment by j-kawasaki** [comment]
おそらく送信データ量が増えて，pickleで圧縮したデータが途中で途切れて送受信されていると思う．
1024バイト以上のデータを送るときは分割して送信するようにする
